config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /fr|en/ do
    ActiveAdmin.routes(self)
    devise_for :users

    if Rails.env.development?
      root to: 'places#index'
    elsif Rails.env.production?
      root to: 'pages#home'
    end
    resources :places
    resources :contacts
    post 'places/filters', 'places#filters'
    post 'places/monuments_filter', 'places#monuments_filter'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
  reverse_geocoded_by :lat, :lng
  after_validation :reverse_geocode

  has_one :monument_summary
  has_one :wall_summary

  accepts_nested_attributes_for :monument_summary
  accepts_nested_attributes_for :wall_summary

  scope :find_by_kind, -> (kind) { where(kind: kind).order('name ASC') }
  scope :monument_by_category, -> (category) { where(kind: 'Monument')
                                               .where(sub_category_fr: category)
                                               .order('name ASC')}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, except: :filters
  before_action :authenticate_user!
  before_action :set_locale

  def set_locale
    I18n.locale = params.fetch(:locale, I18n.default_locale).to_sym
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :new, :create ]
  skip_before_action :verify_authenticity_token
  before_action :set_contact, only: [:edit]

  def new
    @new_contact = Contact.new
  end

  def create
    @new_contact = Contact.new contacts_params

    respond_to do |format|
      if @new_contact.save
        format.js
        flash[:notice] = t('controllers.contacts.success')
        AdminNotificationMailer.new_contact_notification(@new_contact).deliver
        format.html { redirect_back(fallback_location: root_path) }
      else
        format.js { render :new }
        format.html do
          flash[:alert] = t('controllers.contacts.fail')
          render :new
        end
      end
    end
  end

  def edit
  end

  private

  def contacts_params
    params.require(:contact).permit(:name,
                                    :email,
                                    :content)
  end

  def set_contact
    @contact = Contact.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :filters ]
  before_action :set_places, only: [:show]

  include GeocoderHelper

  def index
    center_map(Place)
    monument_sub_categories_names
    places_markers
    filters
    respond_to do |format|
      format.js
      format.html
    end
  end

  def places_markers
    @all_places = Place.all
    @all_places = @all_places.decorate
    display_places_markers(@all_places)
  end

  def filters
    place_kind            = params[:kind]
    monument_sub_categoy  = params[:monument_cat]

    @filtered_places = []

    if place_kind.present?
      @filtered_places = Place.find_by_kind(place_kind)
    elsif monument_sub_categoy.present?
      monuments_sub_categories_filters(monument_sub_categoy)
    end

    @filtered_places = @filtered_places.map {|place| place.decorate }

    respond_to do |format|
      format.js
      format.html
    end

    gon.markers = @places_markers
  end

  private

  def monuments_sub_categories_filters(category_params)
    if category_params == (I18n.t 'all_categories')
      @filtered_places = Place.find_by_kind('Monument')
    elsif category_params != @all_categories
      @filtered_places = Place.monument_by_category(category_params)
    end
  end

  def monument_sub_categories_names
    @all_categories = (I18n.t 'all_categories')
    @monument_sub_categories_names =
      Place.pluck(:sub_category_fr)
           .uniq
           .unshift @all_categories
  end

  def set_places
    @place = Place.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def recognize_path
    Rails.application.routes.recognize_path(request.referrer)
  end

  def is_home?
    controller_name == 'pages' && action_name == 'home'
  end

  def come_from_home?
    controller_name == 'places' && action_name == 'index' && recognize_path[:controller] == "pages"
  end
end

app/helpers/geocoder_helper.rb
module GeocoderHelper
  def center_map(collection)
    location = "Montreal, QC"
    within_area(collection, geocoder(location))
  end

  def within_area(collection, box)
    @geocoded_places = collection.within_bounding_box(box)
  end

  def geocoder(location)
    center = Geocoder.search(location)
    bounds = center.first.geometry['bounds'] || Geocoder.search("Montreal, QC, Canada").first.geometry['bounds']
    box = [
      bounds['southwest']['lat'],
      bounds['southwest']['lng'],
      bounds['northeast']['lat'],
      bounds['northeast']['lng'],
    ]
  end

  def build_places_markers(places)
    places_coordinates = []
    places_markers     = []

    places.each do |place|
      coord = {
        lat: place.lat,
        lng: place.lng
      }
      places_coordinates << coord

      marker = {}

      marker[:id] = "place_#{place.id}"
      marker[:place_lat] = place.lat
      marker[:place_lng] = place.lng
      marker[:infowindow] = render_to_string(
                                partial: "infowindow.html.slim",
                                formats: [:html],
                                layout: false,
                                locals: {place: place},
                                cache: true)

      places_markers << marker
    end
    return places_markers
  end

  def display_places_markers(places)
    @places_markers = build_places_markers(@all_places)
  end
end

app/helpers/place_helper.rb
module PlaceHelper
  def place_contact(place)
    if place.website.present?
      label = Place.human_attribute_name(:website)
      website = place.website.split(',')[0]
      phone   = place.phone
      content_tag(:div) do
        concat (link_to label, website, target: '_blank') + ' - ' + phone + "<br>".html_safe + "<hr>".html_safe
      end
    end
  end

  def is_monument?(place)
    place.kind == 'Monument'
  end

  def is_wall?(place)
    place.kind == 'Wall'
  end

  def kinds_collection
    {
      "Monument": "Monuments",
      "Wall": "Fresques murales",
      "Centre communautaire": "Centres communautaires",
      "Cinéma,Théâtre": "Cinémas, Théâtres",
      "Centre des loisirs": "Centres des loisirs",
      "Bibliothèque,Centre communautaire,Salle de spectacle": "Bibliothèques, Centres communautaires, Salles de spectacles",
      "Salle de spectacle,Musée municipal": "Salles de spectacles, Musées municipaux",
      "Bibliothèque": "Bibliothèques",
      "Salle de spectacle": "Salles de spectacles",
      "Église": "Églises"
    }
  end

  def places_results_header(kind)
    kinds_collection.select do |csv_kind, real_kind|
      csv_kind = csv_kind.to_s
      unless csv_kind.nil? || kind.nil?
        if kind.start_with?(csv_kind) && kind.end_with?(csv_kind)
          return real_kind
        end
      end
    end
  end

  def kind_header_color(kind)
    kind = places_results_header(kind)
    case kind
    when "Centres communautaires"
      "com_centers"
    when "Fresques murales"
      "wall"
    when "Monuments"
      "monuments"
    when "Cinémas, Théâtres"
      "cin_the"
    when "Théâtres"
      "the"
    when "Centres des loisirs"
      "hobby_cent"
    when "Cinémas"
      "cin"
    when "Bibliothèques, Centres communautaires, Salles de spectacles"
      "lib_com_spe"
    when "Salles de spectacles, Musées municipaux"
      "spe_mus"
    when "Musées municipaux"
      "mus"
    when "Bibliothèques"
      "lib"
    when "Salles de spectacles"
      "spe"
    when "Églises"
      "church"
    end
  end
end

app/views/contacts/_contact.slim
.wrapper-contact
  h4.slider-intro

  = render 'form', new_contact: @new_contact

app/views/contacts/_form.slim
p.contact-intro= "Des questions ou pistes d'améliorations? C'est ici."

= simple_form_for new_contact, html: { class: 'contact-form' }  do |f|

  = f.input      :name,
                 label: false,
                 placeholder: I18n.t('contact.name'),
                 require: true

  = f.input      :email,
                 label: false,
                 placeholder: I18n.t('contact.email'),
                 required: true

  = f.text_area :content,
                placeholder: I18n.t('contact.text_area')

  .contact-submit
    = f.button :submit, I18n.t('contact.contact_submit'),
                        id: 'contact_submit'

app/views/contacts/new.js.erb
$("#contactContainer").html("<%= j render 'contact', new_contact: @new_contact %>");

app/views/contacts/new.slim
#contact-form-wrapper
  .container
    .col-xs-12.col-md-6.col-md-offset-3
      .contact-header
        = link_to places_path do
          = image_tag 'logo-montreel.svg', class: 'contact-logo'
        = link_to 'Retour à la carte', places_path, class: 'back-to-map'
      .contact-form
        = render 'form', new_contact: @new_contact

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Montreel
    = favicon_link_tag 'favicon-montreel.png'
    = csrf_meta_tags
    = action_cable_meta_tag

    link href="//fonts.googleapis.com/css?family=Open+Sans:400,300,700|Raleway:400,100,300,700,500|Lora:400,700'" rel="stylesheet"

    meta content="width=device-width, initial-scale=1" name="viewport" /
    meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" /
    = stylesheet_link_tag    'application', media: 'all'

  body

    = render 'shared/flashes'
    #resultsSliderwrapper
      #resultsSliderContainer
      #closeSliderBtn

    #contactContainer
    #contactOverlay

    = render 'shared/ajax_spinner'

    = yield
    = render "shared/analytics"

    = include_gon
    = javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}"

    = javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js"

    = javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js"

    = javascript_include_tag 'application'

    = yield(:places_map)

app/views/pages/home.html.slim
= render "shared/welcome_overlay"

app/views/places/_filter_results.html.slim
#resultsSliderContainer

app/views/places/_filters.html.slim
#places-kind-filters
  .filter-button class="dropdown-btn" data={ 'remote-url' => places_filters_path,
                                             'kind' =>  "Monument"}
    a= "Monuments"

  .monument-categories-filter-wrapper
    .categories-dropdown.monuments-filter-btn
      - @monument_sub_categories_names.each do |category|
        span class="monuments-filter-btn_#{category}" data={'remote-url': "filters", "monument_cat": "#{category}"}
          = category

  - kinds_collection.except(:Monument).each do |kind, label|
    .filter-button.places-kind-but-monuments data={ 'remote-url' => places_filters_path,
                                                    'kind' =>  "#{kind}"}
      a= "#{label}"

- if current_user && current_user.admin = true
  = link_to "Admin sign out", destroy_user_session_path, method: :delete

app/views/places/_infowindow.html.slim
.iw-content-wrapper data={'place_kind': "#{place.kind}",
                          'monument_sub_category': "#{place.sub_category_fr}",
                          'id': "#{place.id}"}

  h4.iw-title
    = place.name
  .iw-contact-info

    - if is_monument?(place)
      span class="iw-artist-name"
        = place.artist_full_name
      hr
      span class="iw-location"
        = place.address
        = place.location
      hr
      span= place.category_fr
      br
      span= place.sub_category_fr
      br
      span= place.techo_fr

    - elsif is_wall?(place)
      h5= place.wall_artist
      span class='iw-location'
        = place.address
        br
        = "Organisation: #{place.organisation}"
        hr
        - if place.program.present?
          = "Program: #{place.program}"

      .iw-picture
        = image_tag "#{place.image}", class: 'wall-image'

    - else
      span= place_contact(place)
      span= place.address
      span= place.borough


  - unless is_monument?(place) || is_wall?(place)
    p.iw-desc
      - desc = place.description
      = desc ? desc : t('no_description')

app/views/places/_kind.html.slim
#results-header
  .circle class="#{kind_header_color(places.first.kind)}"

  h5
    = places_results_header(places.first.kind)


- places.each do |place|
  .places data={'latitude' =>  "#{place.lat}",
                'longitude' =>  "#{place.lng}",
                'id' => "place_#{place.id}"}

    h5= place.name.downcase.capitalize
    p class='borough'
      = place.borough
    - if place.description.present?
      p= place.description.truncate(250, omission: '...')

app/views/places/_map.html.erb
<% content_for(:places_map) do %>
  <script>
    $(document).ready(function() {

      var markersData, markers, infoWindows, mcOptions;

      markersData = <%= raw @places_markers.to_json %>;

      // for clusters
      markers = [];

      // for closing them
      openedInfoWindow = [];

      mcOptions = {
        gridSize: 80,
        minimumClusterSize: 6
      };

      function recenterMap() {
        // on window resize
        google.maps.event.addDomListener(window, 'resize', function() {
          var center = map.getCenter();
          google.maps.event.trigger(map, "resize");
          map.setCenter(center);
        });

        // on nav click
        $( ".filter-button" ).click(function() {
          var center = map.getCenter();
          google.maps.event.trigger(map, "resize");
          map.setCenter(center);
          map.setZoom(11);
        });

        if ($('#places-map').hasClass('newMapWidth')) {
          var center = map.getCenter();
          google.maps.event.trigger(map, "resize");
          map.setCenter(center);
          map.setZoom(11);
        }
      }

      function closeInfoWindow() {
        $( ".filter-button" ).click(function() {
          for (var i=0; i < openedInfoWindow.length; i++) {
            openedInfoWindow[i].close();
          }
        });
        $('span[class*="monuments-filter-btn"]').click(function() {
          for (var i=0; i < openedInfoWindow.length; i++) {
            openedInfoWindow[i].close();
          }
        });
      }

      function hideMarkersOnKindClick() {
        var placeKind, markerPlaceKind;
        $( ".filter-button" ).click(function() {
          placeKind = $(this).attr('data-kind')
          for (var i = 0; i < markers.length; i++){
            markerPlaceKind = markers[i].place_kind
            if (markerPlaceKind == placeKind) {
              markers[i].setVisible(true)
            } else {
              markers[i].setVisible(false)
            }
          }
        });
        $('span[class*="monuments-filter-btn"]').click(function() {
          var monument_sub_category, markerMonumentSubCategory;
          for (var i = 0; i < markers.length; i++){
          monument_sub_category = $(this).attr('data-monument-cat')
            markerMonumentSubCategory = markers[i].monument_sub_category
            if (markerMonumentSubCategory == monument_sub_category) {
              markers[i].setVisible(true)
            } else if (monument_sub_category == "Toutes les catégories" && markers[i].place_kind == "Monument"){
              markers[i].setVisible(true)
            }
            else {
              markers[i].setVisible(false)
            }
          }
        });
      }

      function createMarker (latlng, markerInfowindow) {
        var markerDataKind = $(markerInfowindow).attr('data-place-kind')
        var monument_sub_category = $(markerInfowindow).attr('data-monument-sub-category')
        conditionalMarker(markerInfowindow, markerDataKind)

        var marker = new google.maps.Marker({
          map: map,
          position: latlng,
          icon: icon,
          place_kind: markerDataKind,
          monument_sub_category: monument_sub_category
        });
        markers.push(marker);

        // open IW
        google.maps.event.addListener(marker, 'mouseover', function() {

          var iwContent = markerInfowindow;
          infoWindow = new SnazzyInfoWindow({
            marker: marker,
            content: iwContent,
            closeWhenOthersOpen: true
          });

          infoWindow.open();

          // store IW to be closed on filters click
          openedInfoWindow.push(infoWindow);
          closeInfoWindow()
        });

        // remotely load results list on marker click
        google.maps.event.addListener(marker, 'click', function() {
          return $.ajax({
            url: 'places/filters',
            method: 'POST',
            data: {
              kind: markerDataKind
            },
            success: function(data) {},
            error: (error) => {
              console.log('ajax failed: result loading on marker click');
            }
          });
        });
      }

      function displayMarkers(markersData){
        var bounds = new google.maps.LatLngBounds();
        var places_coordinates = [];
        for (var i = 0; i < markersData.length; i++){
          var latlng = new google.maps.LatLng(markersData[i].place_lat, markersData[i].place_lng);
          var markerInfowindow = markersData[i].infowindow;
          places_coordinates.push(latlng);
          createMarker(latlng, markerInfowindow);
          bounds.extend(latlng);
        }
        // var markerCluster = new MarkerClusterer(map, markers, mcOptions);
        map.fitBounds(bounds);
        hideMarkersOnKindClick();
      }

      function initialize() {
        map = new google.maps.Map(document.getElementById('places-map'), mapOptions);

        infoWindow = new SnazzyInfoWindow({});
        displayMarkers(markersData);
        recenterMap();
      }

      function conditionalMarker (markerInfowindow, markerDataKind) {
        if (markerDataKind == 'Centre communautaire') {
          icon = com_centers
        } else if (markerDataKind == 'Monument') {
          icon = monuments
        } else if (markerDataKind == 'Cinéma,Théâtre'){
          icon = cin_the
        } else if (markerDataKind == 'Théâtre'){
          icon = the
        } else if (markerDataKind == 'Centre des loisirs'){
          icon = hobby_cent
        } else if (markerDataKind == 'Cinéma'){
          icon = cin
        } else if (markerDataKind == 'Bibliothèque,Centre communautaire,Salle de spectacle'){
          icon = lib_com_spe
        } else if (markerDataKind == 'Salle de spectacle,Musée municipal'){
          icon = spe_mus
        } else if (markerDataKind == 'Musée municipal'){
          icon = mus
        } else if (markerDataKind == 'Bibliothèque'){
          icon = lib
        } else if (markerDataKind == 'Salle de spectacle'){
          icon = spe
        } else if (markerDataKind == 'Église'){
          icon = church
        } else if (markerDataKind == 'Wall'){
          icon = wall
        }
      }
      var iconScale = 1.3
      var icon = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#d50000',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }
      var com_centers = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#d50000',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }
      var monuments = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#2962ff',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }
      var cin_the = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#00bfa5',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }
      var the = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#aa00ff',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }
      var hobby_cent = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#64dd17',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }
      var cin = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#ffab00',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }

      var lib_com_spe = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#dd2c00',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }
      var spe_mus = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#3e2723',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }
      var mus = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#263238',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }
      var lib = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#4caf50',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }
      var spe = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#3f51b5',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }
      var church = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#ff9800',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }
      var wall = {
        path: "M4.415,8.829c2.432,0,4.415-1.983,4.415-4.415 C8.829,1.983,6.846,0,4.415,0S0,1.983,0,4.415C0,6.846,1.983,8.829,4.415,8.829z",
        fillColor: '#f7630c',
        fillOpacity: 1,
        anchor: new google.maps.Point(0,0),
        strokeWeight: 0,
        scale: iconScale
      }

      var mapOptions = {
        zoom: 6,
        minZoom:3,
        maxZoom: 16,
        mapTypeId: 'roadmap',
        styles: [ { "featureType": "all", "elementType": "geometry.fill", "stylers": [ { "weight": "2.00" } ] }, { "featureType": "all", "elementType": "geometry.stroke", "stylers": [ { "color": "#9c9c9c" } ] }, { "featureType": "all", "elementType": "labels.text", "stylers": [ { "visibility": "on" } ] }, { "featureType": "landscape", "elementType": "all", "stylers": [ { "color": "#f2f2f2" } ] }, { "featureType": "landscape", "elementType": "geometry.fill", "stylers": [ { "color": "#ffffff" } ] }, { "featureType": "landscape.man_made", "elementType": "geometry.fill", "stylers": [ { "color": "#ffffff" } ] }, { "featureType": "poi", "elementType": "all", "stylers": [ { "visibility": "off" } ] }, { "featureType": "road", "elementType": "all", "stylers": [ { "saturation": -100 }, { "lightness": 45 } ] }, { "featureType": "road", "elementType": "geometry.fill", "stylers": [ { "color": "#eeeeee" } ] }, { "featureType": "road", "elementType": "labels.text.fill", "stylers": [ { "color": "#7b7b7b" } ] }, { "featureType": "road", "elementType": "labels.text.stroke", "stylers": [ { "color": "#ffffff" } ] }, { "featureType": "road.highway", "elementType": "all", "stylers": [ { "visibility": "simplified" } ] }, { "featureType": "road.arterial", "elementType": "labels.icon", "stylers": [ { "visibility": "off" } ] }, { "featureType": "transit", "elementType": "all", "stylers": [ { "visibility": "off" } ] }, { "featureType": "water", "elementType": "all", "stylers": [ { "color": "#46bcec" }, { "visibility": "on" } ] }, { "featureType": "water", "elementType": "geometry.fill", "stylers": [ { "color": "#c8d7d4" } ] }, { "featureType": "water", "elementType": "labels.text.fill", "stylers": [ { "color": "#070707" } ] }, { "featureType": "water", "elementType": "labels.text.stroke", "stylers": [ { "color": "#ffffff" } ] } ]
      };

      initialize();

    });
  </script>
<% end %>

app/views/places/_navmap.html.slim
#navmap
  = render 'filters'
  #logo-nav-map
    = image_tag 'logo-montreel-white.svg'
    span class="year"
      = "© #{Time.now.year}"

app/views/places/_top_nav.slim
#top-nav
  .contact
    = link_to t('nav.contact'), new_contact_path(@new_contact),
                                class: 'openContactBtn desktop-show',
                                remote: true

app/views/places/index.html.slim
- if come_from_home?
  = render "shared/welcome_overlay"
#places-map
= render "navmap"
= render "top_nav"
= render "map"
= render "filter_results"

app/views/shared/_welcome_overlay.html.slim
#white-overlay
#welcome-overlay.transitioned-1s
  - if controller_name == 'pages' && action_name == 'home'
    .home-bg
      .layer.layer1
      .layer.layer2
      .layer.layer3

  .overlay-container
    - if is_home?
      = image_tag 'logo-montreel.svg', class: 'logo-welcome'
      .home-page-into
        p class="text-intro"
          = t('welcome')
    - else
      .places-index-intro
        h4= t('hello')
        p class="text-intro"
          = t('discover') + " " "#{@all_places.count}" + " " + t('public_places')

    - if is_home?
      span id='welcome-btn'
        = link_to t('enter'), places_path
    - else
      span id='close-welcome-btn'
        = t('navigate')